<Project>
  <PropertyGroup Condition="'$(UsingMicrosoftNETSdk)' == 'true'">
    <LangVersion>latest</LangVersion>
    <RollForward>LatestPatch</RollForward>
  </PropertyGroup>

  <PropertyGroup Condition="'$(UsingMicrosoftNETSdk)' == 'true' AND '$(MSBuildProjectName)' != 'Sites.Web.Tests'">
    <BaseOutputPath>$(MSBuildThisFileDirectory)..\output\</BaseOutputPath>
    <OutputPath>$(MSBuildThisFileDirectory)..\output\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup Condition="'$(UsingMicrosoftNETSdk)' == 'true'">
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>BuildTimestamp</_Parameter1>
      <_Parameter2>$([System.DateTime]::Now.ToString("yyyy-MM-dd HH:mm"))</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
